# The ssh publisher is used to send content built on the buildfarm to various
# hosts. There are four different hosts:
# * `repo` is the host configured by the repo recipe and running the
#   building_repository agent. This configuration is required to transmit
#   packages built in the individual source and binary jobs to the repo host to
#   be imported. SSH host and configuration information left unspecified for
#   other hosts defaults to using the repo configuration.
#
# * `docs` is the host for generated documentation. It defaults to a docs
#   directory served by the repo host.
#
# * `rosdistro_cache` is the host containing the rosdistro_cache files
#   generated and used by the buildfarm. The locations of these files are
#   are specified in the rosdistro index and therefore must be a location that
#   is accessible using the url configured in the rosdistro index.
#
# * `status_page` is the host containing the status pages generated by the
#   build farm. This is usually the `status_page` subdirectory of the
#   repository host.
#
# Each host also has several fields. Any fields not defined for the `docs`,
# `rosdistro_cache`, or `status_page` host will fall back to the values for the
# `repo` host.
# * `_hostname` is the valid ssh hostname that the ssh publisher will use.
# * `_port` is the port to use when connecting via ssh.
# * `_timeout` is the timeout length when establishing an ssh connection in
#   milliseconds.
# * `_root_dir` is the directory that published files will be nested under.
#   The root_dir for the repo host should not be changed unless you are also
#   customizing other parts of the ros_buildfarm stack. Other root directories
#   are designed to work well sharing the repo host but can be changed to
#   whatever is appropriate if using externally managed hosts.
default['ros_buildfarm']['ssh_publisher']['repo_hostname'] = 'repo'
default['ros_buildfarm']['ssh_publisher']['repo_port'] = 22
default['ros_buildfarm']['ssh_publisher']['repo_timeout'] = 30000
default['ros_buildfarm']['ssh_publisher']['repo_root_dir'] = '/var/repos/ubuntu/building/queue'
default['ros_buildfarm']['ssh_publisher']['docs_root_dir'] = '/var/repos/docs'
default['ros_buildfarm']['ssh_publisher']['rosdistro_cache_root_dir'] = '/var/repos/rosdistro_cache'
default['ros_buildfarm']['ssh_publisher']['status_page_root_dir'] = '/var/repos/status_page'
default['ros_buildfarm']['ssh_publisher']['ci_archives_root_dir'] = '/var/repos/ci_archives'

